acm-tenant-gitops:
  name: acm-poc-data-engineering-gitops
  channels:
    infra:
      spec:
        type: Git
        pathname: https://github.com/finastra-engineering/acm-poc-data-engineering-gitops
        secretRef:
          name: acm-github-token
    sample-quarkus-app-helm:
      spec:
        type: HelmRepo
        pathname: https://finastra-engineering.github.io/sample-quarkus-app-chart
